### ISSUE TITLE
nick will be changed

### ISSUE THREAD

**Issue by kuwaity33** [atheme/atheme#872] opened 2022-05-23 14:47 UTC
Hello,

How to activate kill nick
Your nick will be changed in 60 seconds if you do not comply
Note that I did the following method in the config file
atheme.conf
loadmodule "modules/nickserv/enforce";
uflags = { hidemail; enforce; };
enforce_prefix = "Guest";

What is the solution, thank you

**Comment by ilbelkyr** [comment] 2023-05-13 15:27
From just the information provided, it's a little difficult to figure out the issue – that said, keep in mind `general::uflags` only applies to newly created accounts; existing accounts can enable the flag using NickServ's `SET` command.

Closing this issue as not a bug; for general support questions, you might want to try `#atheme` on Libera Chat as well!

**Closed by ilbelkyr** 2023-05-13 15:27 UTC
