### ISSUE TITLE
ChanServ won't let anyone register

### ISSUE THREAD

**Issue by Brand3n** [atheme/atheme#452] opened 2015-02-11 16:22 UTC
After c50f527 ChanServ doesn't let anyone register channels, even if the number of channels they have registered is 0. The error message they get is "You have too many channels registered." Reverting lets everything work again.

**Comment by B00mX0r** [comment] 2015-02-11 16:47
I see this issue as well for non-opers.

**Comment by aaronmdjones** [comment] 2015-02-11 16:48
Is it possible to set max chans to 0? If so, have you done that? I see no check for whether it's zero before comparing against it; this is just speculation though.

**Comment by dwfreed** [comment] 2015-02-11 16:49
Giving foundership to groups is likewise broken, because the can_register_channel validators for groups and users only return true if the entity has the REGNOLIMIT flag, or if the user has the REGNOLIMIT soper privilege, and that is now the final check in myentity_can_register_channel.

**Comment by Brand3n** [comment] 2015-02-11 16:56
> I see this issue as well for non-opers.

Yes, normal users can't register channels, as well as opers even with the user:regnolimit privilege.

> Is it possible to set max chans to 0? If so, have you done that?

I don't know if it's possible, but "/os info" provides this:
```
-OperServ- Maximum number of channels that one user can own: 5
```

**Comment by dwfreed** [comment] 2015-02-11 16:57
The only semi-sane way I see to fix this codepath is to move the myentity_count_channels_with_flagset call into the can_register_channel validators for groups and users.  Another way to fix this would be to have exttargets hook channel_acl_change and cancel the addition of +F to the ACL if it's for an exttarget.

**Comment by B00mX0r** [comment] 2015-02-11 17:06
Brand3n, what I meant is that I was able to register a channel as an era, but couldn't as a normal user.

**Comment by spb** [comment] 2015-02-11 18:04
The problem is that the referenced commit completely changes the meaning of existing can_register_channel validators. These functions were originally used to answer the question "can this entity override channel registration limits"; now they're being used to mean "can this user register a channel if the channel registration limit allows it".

Even if the existing validators are changed to account for this, it still breaks the existing functionality of the regnolimit privilege/flag. I would suggest reverting this pending a correct solution to the bug it attempted to fix.

**Comment by spb** [comment] 2015-02-11 18:09
c50f527 reverted -- this should be fixed now.

**Closed by spb** 2015-02-11 18:09 UTC
