### ISSUE TITLE
Fatal Error during Make

### ISSUE THREAD

**Issue by zonidjan** [atheme/atheme#692] opened 2020-03-21 01:44 UTC
See #679 

`serno.h` is not present in the latest tarball (downloaded via https://atheme.github.io/ "Download" button or equivalently from GitHub releases)

**Comment by alyx** [comment] 2020-06-06 22:33
Cannot reproduce using the [most recent tarball](https://github.com/atheme/atheme/releases/download/v7.2.10-r2/atheme-v7.2.10-r2.tar.xz); can you please confirm if this is the tarball you're using or if this issue is still persisting?

**Comment by ctria** [comment] 2020-06-11 22:29
I can reproduce it with the most recent tarball:
```bash
$ wget -q  https://github.com/atheme/atheme/releases/download/v7.2.10-r2/atheme-v7.2.10-r2.tar.xz -O -| tar -tJ | grep -c serno.h
0
```

**Comment by zonidjan** [comment] 2020-06-11 22:46
Hi,

Looking at the `include/Makefile`, it attempts to generate `serno.h` from a git command. Unfortunately, it silences errors from that command: otherwise, there would be a much more useful error message (something along the lines of "git: not found"). However, I'm frankly not sure why git would be a requirement to use a prepackaged release. Many distros do not include git by default and many people do not have git installed.

My issue was submitted in March. The previous issue was submitted in December. I'm not sure what other tarball either of us would have been using. A good assumption would be 'the one that has been current for 2 years', as is indeed the case.

**Comment by zonidjan** [comment] 2020-06-11 23:13
The code in master has changed quite a bit, and looks like it is no longer dependent on git to create `serno.h` (although it won't be valid if git is not present).

However, on the topic of abusing git to do things it wasn't meant to do, `git log` is meant to be used by humans, not scripts. https://github.com/atheme/atheme/blob/master/include/atheme/mkserno.sh#L17

Try this:
```
wget https://github.com/atheme/atheme/releases/download/v7.2.10-r2/atheme-v7.2.10-r2.tar.xz
tar -xf atheme-v7.2.10-r2.tar.xz 
cd atheme-v7.2.10-r2
git config log.showsignature true
git log -n1 --abbrev=20 --format='%h'
```

And look at how wonderfully it breaks. Now try this:

```
git rev-parse --short=20 HEAD
```

And look at how wonderfully it *works* because it's *meant* to be used by a script.

**Comment by ctria** [comment] 2020-06-12 06:07
I confirm that installing git solved this for me :)

I was building a slim docker image thus git was not part of the default installation.

**Comment by aaronmdjones** [comment] 2020-06-12 07:12
@zonidjan Thanks for the feedback & better command.
@ctria Closing as you have indicated the problem is resolved.

**Closed by aaronmdjones** 2020-06-12 07:12 UTC
