### ISSUE TITLE
Users should be able to receive their uncloaked DNS as a vhost

### ISSUE THREAD

**Issue by B00mX0r** [atheme/atheme#447] opened 2015-02-03 19:09 UTC
On InspIRCd, when I try to assign a user their uncloaked DNS as their vhost (e.g. blahblah.blahblah.isp.net), it'll say the vhost is assigned, but then act as though the user doesn't have a vhost. This is a very minor issue, and I'm reporting it because it's important for my specific IRC environment (webirc + full cloaking). I'm filing it under Atheme, since /chghost doesn't have this behavior. I won't be surprised if this is wontfix.

**Comment by Mikaela** [comment] 2015-02-03 19:12
If I understand your issue correctly, you want to disable cloaking in InspIRCd or the user should use `/msg hostserv off`.

```
015-02-03 21:11:48+0200 -- HostServ: ***** HostServ Help *****
2015-02-03 21:11:48+0200 -- HostServ: Help for OFF:
2015-02-03 21:11:48+0200 -- HostServ:  
2015-02-03 21:11:48+0200 -- HostServ: Deactivates the vHost currently assigned to the nick in use.
2015-02-03 21:11:48+0200 -- HostServ: When you use this command, any user who performs a /whois
2015-02-03 21:11:48+0200 -- HostServ: on your nick will see your real IP address.
2015-02-03 21:11:48+0200 -- HostServ:  
2015-02-03 21:11:48+0200 -- HostServ: For permanent removal of your vHost, please see network staff.
2015-02-03 21:11:48+0200 -- HostServ:  
2015-02-03 21:11:48+0200 -- HostServ: Syntax: OFF
2015-02-03 21:11:48+0200 -- HostServ:  
2015-02-03 21:11:48+0200 -- HostServ: Examples:
2015-02-03 21:11:48+0200 -- HostServ:     /msg HostServ OFF
2015-02-03 21:11:48+0200 -- HostServ: ***** End of Help *****
```

and another issue is that this help text is a little misleading as it hints that your real IP address would be protected under the vhost which is not the case.

**Comment by Mikaela** [comment] 2015-02-03 19:19
The lines in example configs that might interest you if my previous comment is correct.

* https://github.com/atheme/atheme/blob/atheme-7.2.5/dist/atheme.conf.example#L638
* https://github.com/inspircd/inspircd/blob/v2.0.18/docs/conf/modules.conf.example#L487

**Comment by B00mX0r** [comment] 2015-02-03 19:34
I think I was a bit unclear. Let's say I send a webirc command which sets my reversed IP to oper.network.com (just an example). With cloaking set to full, it would cloak this. However, let's say I want to make their host oper.network.com. I should be able to do this, but I can't, since Atheme just cloaks it again (turning it into the same gibberish it was without a vhost). /msg HostServ off will cloak it normally, so that doesn't make a difference.

I see your point about disabling InspIRCd cloaking, though I consider that a workaround given that it doesn't issue the host on /ns identify, and it doesn't show in /ns info. Again, I won't be surprised if this is a wontfix.

**Comment by GLolol** [comment] 2015-02-03 19:50
I think `/hostserv request` should have the ability to let users request their Vhost removed entirely.

**Comment by kaniini** [comment] 2015-02-03 23:06
@GLolol a reasonable request, but declined for Atheme.

Closing accordingly.

**Closed by kaniini** 2015-02-03 23:06 UTC

**Comment by GLolol** [comment] 2015-02-03 23:56
That was not an official feature request, but an idea (I know atheme is going EOL it's been like that for a while). @B00mX0r's on shalture is.

**Comment by B00mX0r** [comment] 2015-02-04 03:56
This is a bug report, not a feature request. Were you closing GLolol's idea or is this wontfix?

**Comment by kaniini** [comment] 2015-02-04 04:14
It is not a bug and now it is also locked.
