### ISSUE TITLE
ChanFix module is still loaded even if commented out on config

### ISSUE THREAD

**Issue by westor7** [atheme/atheme#700] opened 2020-05-28 15:59 UTC
Hello,

I am using 7.3.0-rc2 version, i have commented out the module but it keeps connecting after a restart the 'chanfix' service, there are some errors when i force a MODUNLOAD command.

Atheme.conf:

```
#loadmodule "modules/chanfix/main";

#chanfix {
	/* (*)nick
	 * The nickname we want the client to have.
	 */
#	nick = "ChanFixServ";

	/* (*)user
	 * The username we want the client to have.
	 */
#	user = "bot";

	/* (*)host
	 * The hostname we want the client to have.
	 */
#	host = "services.network.gr";

	/* (*)real
	 * The GECOS of the client.
	 */
#	real = "Channel Alt IRC Service";

	/* (*)autofix
	 * Automatically fix channels if they become opless and meet fixing
	 * criteria.
	 */
#	autofix;
#};
```

Before i use MODUNLOAD i used MODLIST to verify that module is still loaded because i set in config to not, and it was:

```237: chanfix/main         [0x7fa6525ea000]```

MODUNLOAD force errors:

```[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.
[2020-05-28 17:23:02] (patricia.c:628 mowgli_patricia_elem_find): warning: assertion 'key != ((void *)0)' failed.

```

- Thanks!

**Comment by ilbelkyr** [comment] 2021-02-11 05:39
apologies that we took so long to respond here. I suspect services may be loading `chanfix/main` to satisfy the database dependency on it. You may need to manually edit your `services.db` file – taking care to keep a backup, obviously – and remove any `CFDBV`, `CFCHAN`, `CFOP` and `CFMD` entries, as well as the `MDEP` entry that specifies `chanfix/main`.

(I've found some other issues with the chanfix code that may explain the assertion failures you see after unloading the module. That should hopefully be fixed on master now, though your intent is to avoid loading the module in the first place anyway.)

**Comment by ilbelkyr** [comment] 2021-02-14 10:50
(closing as I think that'll solve your issue – I can't reproduce it otherwise – please do poke if it persists!)

**Closed by ilbelkyr** 2021-02-14 10:50 UTC
